version: '3.9'
services:
  mysql:
    image: "mysql:${MYSQL_VERSION}"
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: "${PREFIX}_db"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE_NAME}"
      MYSQL_USER: "${MYSQL_DATABASE_USER}"
      MYSQL_PASSWORD: "${MYSQL_DATABESE_PASSWORD}"
    restart: unless-stopped
    env_file: .env
    networks:
      - app-network
  
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: "${PREFIX}_node"
    command: "npm run serve"
    networks:
      - app-network
    volumes:
      - ./vue-app:/app

  wordpress:
    build: 
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        MYSQL_DATABASE_NAME: "${MYSQL_DATABASE_NAME}"
        MYSQL_DATABASE_USER: "${MYSQL_DATABASE_USER}"
        MYSQL_DATABESE_PASSWORD: "${MYSQL_DATABESE_PASSWORD}"
    container_name: "${PREFIX}_web"
    depends_on:
      - mysql
    ports:
      - "${LOCAL_PORT}" # 同時に起動したいなどの理由がなければ同じポートで大丈夫です。
    volumes:
      - ../wordpress/:/var/www/html/
    env_file:
      - .env
      - php/environments/wordpress.env
    environment:
      WORDPRESS_DB_HOST: "mysql:3306" # DBのポートとイメージを指定する
      WORDPRESS_DB_USER: "${MYSQL_DATABASE_USER}" # MYSQL_USER
      WORDPRESS_DB_PASSWORD: "${MYSQL_DATABESE_PASSWORD}" # MYSQL_PASSWORD
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE_NAME}" # MYSQL_DATABASE
    networks:
      - app-network
networks:
  app-network:
volumes:
  mysql_data:
